# Generated by Django 3.0.2 on 2020-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_speech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdata',
            name='file_name',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
