# Generated by Django 3.0.2 on 2020-01-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_speech', '0002_auto_20200103_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.CharField(max_length=255)),
            ],
        ),
    ]
