# Generated by Django 3.0.2 on 2020-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_speech', '0003_speechtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtext',
            name='uploaded_text_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
